/**
 * 古蜀秘档 · 内置广告主资料
 * 无外链时使用 landing/index.html?slot=...
 */
window.MATCH3_SPONSORS = {
  level_start: {
    sponsor: "蜀光头灯",
    headline: "入墓之前，先亮一手",
    teaser: "考古级头灯 · 长续航 · 防雾镜片 · 探方必备",
    icon: "🔦",
    badge: "探方启程",
    price: "¥68",
    priceNote: "探险套装券",
    bullets: ["320 流明高亮", "8 小时续航", "附赠红滤镜"],
    cta: "领取探方券",
    cpm: 24,
    cpc: 1.8,
  },
  level_end: {
    sponsor: "青铜文创社",
    headline: "过关留念，带走一段古蜀",
    teaser: "纵目面具书签 · 神树徽章 · 通关纪念礼盒",
    icon: "🏺",
    badge: "过关庆祝",
    price: "8.5 折",
    priceNote: "通关专属",
    bullets: ["博物馆联名", "礼盒包邮", "限量编号"],
    cta: "领取文创券",
    cpm: 26,
    cpc: 2.0,
  },
  expedition_go: {
    sponsor: "墓冢安全险",
    headline: "深入探点，多一份保障",
    teaser: "户外意外险 · 24h 救援 · 探墓小队专享价",
    icon: "🛡",
    badge: "探点进发",
    price: "¥9.9/月",
    priceNote: "首月体验",
    bullets: ["意外医疗", "定位救援", "随买随停"],
    cta: "了解保障",
    cpm: 28,
    cpc: 2.2,
  },
  continue_play: {
    sponsor: "蜀地文旅",
    headline: "三星堆 · 金沙 · 一条线玩透",
    teaser: "联票优惠 · 导览讲解 · 周末出发",
    icon: "🗺",
    badge: "继续探方",
    price: "联票 -30",
    priceNote: "游戏用户专享",
    bullets: ["含讲解", "免排队通道", "亲子友好"],
    cta: "查看线路",
    cpm: 22,
    cpc: 1.6,
  },
  reward_hammer: {
    sponsor: "洛阳铲工坊",
    headline: "观看赞助 · 获赠清理道具",
    teaser: "⛏ ×1 · 清除单格封土/障碍",
    icon: "⛏",
    badge: "补给赞助",
    price: "免费",
    priceNote: "观看即得",
    bullets: ["本局可用", "不消耗库存", "赞助支持开发"],
    cta: "了解更多",
    cpm: 32,
    cpc: 0.8,
    rewarded: true,
  },
  reward_shuffle: {
    sponsor: "扰层罗盘",
    headline: "观看赞助 · 获赠重排道具",
    teaser: "🔀 ×1 · 无步数消耗重排棋盘",
    icon: "🔀",
    badge: "补给赞助",
    price: "免费",
    priceNote: "观看即得",
    bullets: ["本局可用", "破局专用", "赞助支持开发"],
    cta: "了解更多",
    cpm: 30,
    cpc: 0.8,
    rewarded: true,
  },
};
